# Quarkus Configuration
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Security
smallrye.jwt.sign.key.location=${SMALLRYE_JWT_SIGN_KEY_LOCATION:privateKey.pem}
mp.jwt.verify.issuer=unity-catalog-acs-bff
mp.jwt.verify.publickey.location=${MP_JWT_VERIFY_PUBLICKEY_LOCATION:publicKey.pem}
quarkus.smallrye-jwt.token.header=Cookie
quarkus.smallrye-jwt.token.cookie-name=bff_jwt
quarkus.smallrye-jwt.auth-mechanism-fallback=true

# REST Client
databricks-api/mp-rest/url=${DATABRICKS_API_MP_REST_URL:https://databricks-instance.com}

# HATEOAS
quarkus.hal.json.enabled=true

# Health
quarkus.smallrye-health.root-path=/health

# Metrics
quarkus.micrometer.export.prometheus.path=/metrics

# OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
mp.openapi.extensions.smallrye.info.title=ACS Backend API
mp.openapi.extensions.smallrye.info.version=1.0.0

# OpenTelemetry
quarkus.otel.enabled=true
quarkus.otel.exporter.otlp.endpoint=${QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
quarkus.otel.service.name=acs-backend
quarkus.otel.resource.attributes=${QUARKUS_OTEL_RESOURCE_ATTRIBUTES:deployment.environment=development}
