apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acs-backend.fullname" . }}-config
  labels:
    {{- include "acs-backend.labels" . | nindent 4 }}
data:
  DATABRICKS_API_MP_REST_URL: {{ .Values.appConfig.databricksUrl | quote }}
  QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.appConfig.otelEndpoint | quote }}
  QUARKUS_OTEL_RESOURCE_ATTRIBUTES: "deployment.environment={{ .Values.appConfig.environment }}"
