{{- if .Values.security.pemKeysEnabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acs-backend.fullname" . }}-keys
  labels:
    {{- include "acs-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.security.publicKeyBase64 }}
  publicKey.pem: {{ .Values.security.publicKeyBase64 }}
  {{- end }}
  {{- if .Values.security.privateKeyBase64 }}
  privateKey.pem: {{ .Values.security.privateKeyBase64 }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acs-backend.fullname" . }}-auth
  labels:
    {{- include "acs-backend.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.postgresql.password | b64enc | quote }}
  oidc-secret: {{ .Values.oidc.clientSecret | b64enc | quote }}

